name: Habit Tracker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Test Python Syntax
        run: |
          python -m py_compile app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "65.2.3.208"
          username: "ubuntu"
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            if [ ! -d ~/Habit-Tracker ]; then
              git clone https://ramakrishnanallaganchuram-hash:${{ secrets.GH_PAT }}@github.com/ramakrishnanallaganchuram-hash/Habit-Tracker.git ~/Habit-Tracker
              cd ~/Habit-Tracker
              python3 -m venv venv
              source venv/bin/activate
              pip install flask
            fi
            cd ~/Habit-Tracker
            git pull https://ramakrishnanallaganchuram-hash:${{ secrets.GH_PAT }}@github.com/ramakrishnanallaganchuram-hash/Habit-Tracker.git main
            pkill -f "python app.py" || true
            source venv/bin/activate
            pip install flask
            nohup python app.py > app.log 2>&1 &
            disown
            echo "App started successfully"
